-- ============================================================
-- DATABASE SETUP — Toko Azzahro
-- Jalankan SEMUA baris ini di Supabase SQL Editor
-- ============================================================

-- 1. Tabel Kasir / Staf
CREATE TABLE IF NOT EXISTS cashiers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabel Sesi Kasir
CREATE TABLE IF NOT EXISTS cash_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cashier_id BIGINT REFERENCES cashiers(id),
  cashier_name TEXT,
  opened_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  opened_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  opening_amount NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'open',
  closed_at TIMESTAMP WITH TIME ZONE,
  closing_amount NUMERIC,
  summary JSONB DEFAULT '{}',
  notes_open TEXT,
  notes_close TEXT
);

-- 3. Kolom tambahan tabel transactions
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS session_id BIGINT REFERENCES cash_sessions(id);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS cashier_id BIGINT;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS served_by TEXT;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS tx_code TEXT;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS discount_total NUMERIC DEFAULT 0;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS cash_received NUMERIC DEFAULT 0;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS change_amount NUMERIC DEFAULT 0;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS applied_promos JSONB DEFAULT '[]';

-- 4. Kolom tambahan tabel products
ALTER TABLE products ADD COLUMN IF NOT EXISTS parent_sku TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS variant_name TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS variant_options JSONB DEFAULT '[]';
ALTER TABLE products ADD COLUMN IF NOT EXISTS cost_price NUMERIC DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS weight NUMERIC DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS weight_unit TEXT DEFAULT 'g';
ALTER TABLE products ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;

-- 5. Fungsi RPC: potong stok berdasarkan SKU (dipanggil saat checkout kasir)
CREATE OR REPLACE FUNCTION decrement_stock_by_sku(p_sku TEXT, p_qty INTEGER)
RETURNS VOID AS $$
BEGIN
  UPDATE products SET stock = GREATEST(0, stock - p_qty) WHERE sku = p_sku;
END;
$$ LANGUAGE plpgsql;

-- 6. Index untuk performa query
CREATE INDEX IF NOT EXISTS idx_tx_session_id ON transactions(session_id);
CREATE INDEX IF NOT EXISTS idx_sessions_status ON cash_sessions(status);
CREATE INDEX IF NOT EXISTS idx_products_sku ON products(sku);
CREATE INDEX IF NOT EXISTS idx_products_parent_sku ON products(parent_sku);
